
const aviationTopics = [
    // Aircraft & Flight
    "aircraft takeoff roll",
    "airplane rotation point",
    "airplane climb out",
    "aircraft cruise altitude",
    "aircraft descent profile",
    "aircraft final approach",
    "airplane landing rollout",
    "aircraft go-around procedure",
    "airline dispatched flight",
    "aircraft weight and balance",
    "aircraft fuel uplift",
    "airline turnback decision",
    "airplane thrust reversal",
    "aircraft flap extension",
    "aircraft slat deployment",
    "airplane spoiler deployment",
    "aircraft autoland sequence",
    "aircraft crosswind landing",
    "airplane short-field landing",
    "aircraft rejected takeoff",
    "aircraft engine start",
    "airplane engine shutdown",
    "aircraft APU start",
    "aircraft auxiliary power unit",
    "airline dispatch release",
    "aircraft performance calculation",
    "airplane fuel planning",
    "airplane payload calculation",
    "aircraft payload distribution",
    "airplane range capability",
    "aircraft seating configuration",
    "airline cabin layout",
    "aircraft pressurization system",
    "airplane oxygen mask deployment",
    "aircraft evacuation drill",
    "airline passenger boarding",
    "airline boarding announcement",
    "airplane cabin service",
    "airline inflight service",
    "aircraft in-flight checklist",
    "airline crew briefing",
    "pilot flight deck briefing",
    "first officer departure briefing",
    "aircraft maintenance deferment",
    "airline dispatch coordination",

    // Airport Infrastructure
    "airport runway surface",
    "airport runway lighting",
    "airport runway markings",
    "airport taxiway guidance",
    "airport apron layout",
    "airport terminal building",
    "airport passenger gate",
    "airport jet bridge docking",
    "airport baggage handling",
    "airport baggage claim",
    "airport security checkpoint",
    "airport customs processing",
    "airport immigration control",
    "airport control tower",
    "airport radar facility",
    "airport ground power unit",
    "airport fuel farm",
    "airport deicing pad",
    "airport hangar complex",
    "airport maintenance depot",
    "airport cargo terminal",
    "airport apron lighting",
    "airport perimeter security",
    "airport passenger terminal",
    "airport concourse gates",
    "airport terminal signage",
    "airport check-in counters",
    "airport transfer desks",
    "airport information desk",
    "airport lounge facility",
    "airport shuttle bus",
    "airport ground handling",
    "airport fire and rescue",
    "airport wildlife control",
    "airport noise monitoring",
    "airport slot management",
    "airport slot coordination",

    // Cockpit & Flight Deck
    "cockpit primary flight display",
    "cockpit multi-function display",
    "cockpit flight director",
    "flight deck autopilot engaged",
    "flight deck autothrottle",
    "cockpit standby instruments",
    "cockpit engine instruments",
    "cockpit fuel gauges",
    "cockpit electrical buses",
    "flight deck checklist",
    "cockpit crew resource management",
    "cockpit circuit breaker panel",
    "cockpit overhead panel",
    "flight deck door secure",
    "cockpit headset communication",
    "flight deck weather radar",
    "cockpit transponder setting",
    "flight deck GPS navigation",

    // Avionics & Systems
    "aircraft flight management computer",
    "aircraft primary flight display",
    "aircraft navigation display",
    "aircraft weather radar",
    "aircraft traffic collision avoidance",
    "aircraft terrain warning system",
    "aircraft transponder code",
    "aircraft ADS-B transmission",
    "aircraft VHF radio",
    "aircraft HF communication",
    "aircraft satcom antenna",
    "aircraft inertial reference unit",
    "aircraft air data computer",
    "aircraft DME readout",
    "aircraft ILS localizer",
    "aircraft glideslope capture",
    "aircraft VNAV profile",
    "aircraft LNAV guidance",
    "aircraft TCAS resolution",

    // Navigation & Air Traffic Control
    "control tower landing clearance",
    "ground control taxi clearance",
    "approach control handoff",
    "departure clearance delivery",
    "aircraft instrument departure",
    "aircraft instrument arrival",
    "airline filed flight plan",
    "aircraft route clearance",
    "aircraft ATIS advisory",
    "airport NOTAM bulletin",
    "airport runway closure notice",
    "airspace class restriction",
    "aircraft holding pattern",
    "aircraft vectoring to final",
    "aircraft runway crossing clearance",
    "aircraft emergency squawk",

    // Maintenance & Ground Support
    "aircraft pre-flight inspection",
    "aircraft post-flight inspection",
    "aircraft A-check maintenance",
    "aircraft C-check overhaul",
    "aircraft engine borescope",
    "aircraft landing gear service",
    "aircraft tire change",
    "aircraft refuelling operation",
    "aircraft towbarless tow",
    "aircraft pushback procedure",
    "aircraft GPU connection",
    "aircraft APU operation",
    "aircraft potable water service",
    "aircraft lavatory service",
    "aircraft cabin cleaning",
    "aircraft exterior wash",
    "aircraft corrosion inspection",
    "aircraft parts logistics",
    "aircraft maintenance manual",

    // Airlines & Flight Operations
    "airline operations control",
    "airline crew scheduling",
    "airline flight dispatch",
    "airline weight and balance",
    "airline fuel planning",
    "airline turnaround planning",
    "airline loadsheet preparation",
    "airline passenger re-accommodation",
    "airline on-time performance",
    "airline fleet management",
    "airline aircraft leasing",
    "airline spare parts inventory",
    "airline maintenance planning",

    // Runway, Taxiway & Apron Safety
    "runway surface friction test",
    "runway centerline lights",
    "runway threshold markings",
    "runway incursion prevention",
    "taxiway centerline marking",
    "taxiway shoulder inspection",
    "apron stand allocation",
    "apron marshalling signals",
    "pushback and tug operations",
    "aircraft wingtip clearance",
    "foreign object debris sweep",
    "runway rubber removal",
    "runway friction assessment",

    // Passenger Services & Terminal
    "airport check-in kiosk",
    "airport baggage drop",
    "airport oversized baggage",
    "airport priority boarding",
    "airport passenger assistance",
    "airport wheelchair assistance",
    "airport family boarding",
    "airport lounge access",
    "airport fast track security",
    "airport lost and found",
    "airport passenger announcements",

    // Cargo & Ramp Operations
    "aircraft cargo loading",
    "aircraft pallet securing",
    "aircraft ULD handling",
    "airport cargo terminal",
    "airline belly cargo operations",
    "aircraft freight acceptance",
    "aircraft cargo door operation",
    "aircraft bulk cargo restraint",

    // Pilots & Crew
    "pilot type rating training",
    "pilot recurrent simulator",
    "pilot preflight briefing",
    "pilot in-flight decision making",
    "first officer procedures",
    "captain command responsibilities",
    "cabin crew safety briefing",
    "ground crew marshalling",
    "flight crew duty time",
    "pilot logbook entry",

    // Misc Airport Operations
    "airport concession operations",
    "airport traffic flow management",
    "airport emergency response",
    "airport environmental management",
    "airport ground access planning",
    "airport terminal refurbishment",
    "airport apron pavement repair",
    "airport facade signage",
    // Additional Aviation & Airport Phrases
    "aircraft nosewheel steering",
    "aircraft tailstrike prevention",
    "aircraft strobe light operation",
    "aircraft navigation light check",
    "aircraft landing light test",
    "aircraft anti-ice system",
    "aircraft de-ice boot inspection",
    "aircraft pitot static check",
    "aircraft stall warning test",
    "aircraft trim tab adjustment",
    "aircraft aileron control check",
    "aircraft rudder control check",
    "aircraft elevator trim setting",
    "aircraft bulk cargo loading",
    "aircraft cabin crew briefing",
    "aircraft passenger manifest",
    "airline crew manifest",
    "airline dispatch release",
    "airline ground operations",
    "airline baggage reconciliation",
    "airline weight distribution",
    "airline schedule recovery",
    "airline disruption management",
    "airport gate scheduling",
    "airport gate turnaround",
    "airport passenger throughput",
    "airport curbside check-in",
    "airport ground transport",
    "airport quick turns",
    "aircraft smoke detector test",
    "aircraft emergency lighting",
    "aircraft slide arming",
    "aircraft slide deployment drill",
    "aircraft life raft stowage",
    "aircraft ELT placement",
    "aircraft emergency checklist",
    "aircraft engine run-up",
    "aircraft thrust check",
    "aircraft engine bleed air",
    "aircraft fuel tank inspection",
    "aircraft refuel panel access",
    "aircraft filler cap secure",
    "aircraft fueling safety",
    "aircraft fuel quality control",
    "aircraft fuel imbalance",
    "aircraft fuel jettison procedure",
    "aircraft APU bleed air",
    "aircraft avionics cooling",
    "aircraft cabin pressurization",
    "aircraft cabin altitude alert",
    "aircraft cockpit checklist flow",
    "aircraft crew duty roster",
    "pilot briefing notes",
    "pilot weather briefing",
    "pilot NOTAM briefing",
    "pilot alternate planning",
    "airport emergency plan",
    "airport rescue fire",
    "airport RFFS operation",
    "airport fuel farm safety",
    "airport hangar fire drill",
    "airport ground power safety",
    "airport apron vehicle escort",
    "aircraft cargo restraint",
    "aircraft ULD inventory",
    "aircraft cargo acceptance",
    "airline cargo manifest",
    "airport cold chain handling",
    "airline hazardous goods",
    "aircraft dangerous goods",
    "airline crew rostering",
    "airline crew base planning",
    "airline crew layover",
    "airline on-time metrics",
    "airline disruption policy",
    "airline contingency planning",
    "airline SOP compliance",
    "airline safety management",
    "aircraft structural inspection",
    "aircraft rivet check",
    "aircraft panel fasteners",
    "aircraft fuselage inspection",
    "aircraft composite repair",
    "aircraft corrosion control",
    "aircraft life-limited parts",
    "aircraft maintenance release",
    "aircraft technical log",
    "aircraft defect rectification",
    "aircraft deferred defect",
    "aircraft reliability program",
    "airport security patrol",
    "airport CCTV monitoring",
    "airport access control",
    "airport ID badging",
    "airport perimeter patrol",
    "airport perimeter intrusion",
    "airport passenger screening",
    "airport baggage screening",
    "airport hold baggage",
    "airport cabin baggage rules",
    "airport lost baggage tracking",
    "airport baggage tracing",
    "airport transfer baggage",
    "airline interline baggage",
    "airline baggage tag",
    "airport baggage reconciliation",
    "aircraft cabin service carts",
    "aircraft galley restocking",
    "aircraft potable water fill",
    "aircraft waste service",
    "aircraft lavatory servicing",
    "airport catering delivery",
    "airport ground service",
    "aircraft potable water flush",
    "aircraft potable water testing",
    "aircraft potable water connector",
    "aircraft ground cooling",
    "aircraft ground air start",
    "aircraft air start unit",
    "airport engineering works",
    "airport pavement management",
    "airport lighting maintenance",
    "airport signage update",
    "airport navigation aid",
    "airport ILS maintenance",
    "airport glidepath calibration",
    "airport VOR maintenance",
    "airport DME calibration",
    "airport surface movement radar",
    "airport ground surveillance",
    "airport apron management",
    "airport slot allocation",
    "airport queuing management",
    "airport passenger assistance",
    "airline passenger handling",
    "airline disruption care",
    "aircraft cabin communication",
    "aircraft interphone system",
    "aircraft public address",
    "aircraft black box retrieval",
    "airport incident investigation",
    "aircraft bird strike report",
    "airport wildlife strike",
    "aircraft maintenance schedule",
    "airline maintenance tracking",
    "aircraft component change",
    "aircraft engine change",
    "aircraft transponder test",
    "aircraft ELT test",
    "aircraft beacon check",
    "aircraft anti-collision lights",
    "aircraft exterior inspection",
    "aircraft interior inspection",
    "airline passenger service",
    "airport passenger flow",
    "airport queue optimization",
    "airport terminal operations",
    "airport terminal cleaning",
    "airport terminal security",
    "airline revenue protection",
    "aircraft cabin configuration",
    "aircraft seating chart",
    "airline check-in priority",
    "airline standby passenger",
    "airline oversold handling",
    "airline rebooking desk",
    "airport transfer lounge",
    "airport connection signage",
    "airline gate agents",
    "aircraft turn time reduction",
    "aircraft quick maintenance",
    "aircraft component supply",
    "airport logistics hub",
    "airport cargo logistics",
    "aircraft ground tracking",
    "airport gate allocation",
    "airport apron safety briefing",
    "airport vehicle marshalling",
    "aircraft marshaller signals",
    "airport marshalling procedures",
    "aircraft ground movement",
    "airport surface operations",
    "aircraft noise abatement",
    "airport community relations",
    "airline environmental program",
    "airport sustainability plan",
  ];

  export default aviationTopics;
